---
title: "CDOM Process Schedule"
author: "Sebastian DiGeronimo"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
librarian::shelf(
  librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  forcats, lubridate, glue, fs, magrittr, here,
  # broom # optional
  
  # additional
  cli, openxlsx, janitor
)

library("conflicted")

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```

# File Paths
- CDOM schedule in cloud
- inventory sheet in cloud


NEED TO MAKE SURE INVENTORY IS UP TO DATE
- go to `merge_meta_chl_hplc_cdom.Rmd` to update inventory
```{r}
source(here(".Rprofile"))
source(here("scripts", "misc_functions.R"))

schedule_file <- 
  here(cloud_dir, "blank_sheets") %>%
  dir_ls(regexp = "schedule") 

meta_data <-
  cloud_dir %>%
  dir_ls(regexp   = "chl_hplc") %>%
  read.xlsx(sheet = "cdom_progress") %>%
  as_tibble() %>%
  mutate(
    collection_date = excel_numeric_to_date(
      collection_date, 
      include_time = TRUE,
      tz = "UTC")
  ) %>%
  filter(collection_date > as_date("2022-03-25")) %>%
  select(cruise_id, station,	"sample ID" = identifier) %>%
  mutate(sample_number = str_extract(`sample ID`, "-(.*)", group = 1)) %>%
    mutate(
    dups = case_when(
      str_detect(sample_number, "(?i)b$") ~ "dup",
      str_detect(`sample ID`, "(?i)b$") ~ "dup",
      .default = NA)
    )

# 
# # meta_data <-
#    search_meta_folders(
#       .dir_path   = here(cloud_dir, "years"),
#       .sub_folder = "metadata",
#       return_type = "vector") %>%
#     str_subset(
#       str_c("H23138", "WS23061", sep = "|")) %>%
# 
#   dir_ls(
#     regexp = "^[^\\$]*fknms_sample_logsheet"
#   ) %>%
#   map(
#     ~ openxlsx::read.xlsx(.x, sheet = "field_logsheet",
#                           detectDates = TRUE) %>%
#       janitor::clean_names() %>%
#       mutate(sample_number = as.character(sample_number),
#              cruise_id =  str_extract(.x, "\\w{1,2}\\d{4,5}")) %>%
#       filter(str_detect(sample_type, "(?i)cdom"))
#   )# %>%
#   list_rbind() %>% #names()
#   arrange(desc(cruise_id)) %>%
#   select(
#     cruise_id,
#     station,
#     "sample ID" = identifier,
#     sample_number
#   ) %>%
  # mutate(
  #   dups = case_when(
  #     str_detect(sample_number, "(?i)b$") ~ "dup",
  #     str_detect(`sample ID`, "(?i)b$") ~ "dup",
  #     .default = NA
  #   )
#   ) %T>% print()

```


```{r}
loc_dist <-
  schedule_file %>%
  read.xlsx(sheet = "color_code") %>%
  as_tibble()


cdom_cruise <- 
  left_join(meta_data, loc_dist) %>%
  nest(.by = cruise_id)

wb <- loadWorkbook(schedule_file) 



for (i in seq(nrow(cdom_cruise))) {

  sheet_name <- cdom_cruise$cruise_id[i]

  if (any(names(wb) %in% sheet_name)) {
    cli::cli_alert_info(glue("Skipping \"{sheet_name}\""))
      next
  }

  dat_sht <- cdom_cruise$data[[i]]
  
  dup_rows <- which(dat_sht$dups == "dup")
  
  dat_sht <- select(dat_sht, -dups)
  
  cli::cli_alert_info(glue("Adding Cruise: \"{sheet_name}\""))
  
  addWorksheet(wb, sheetName = sheet_name)
  writeData(wb, sheet = sheet_name , startCol = 1, startRow = 1, 
            x = dat_sht)
  
  conditionalFormatting(wb, 
                        sheet_name ,
                        cols = 4,
                        rows = 1:(nrow(dat_sht) + 1), 
                        rule = "near", type = "contains",
                        style = createStyle(bgFill = "#FF0000"))
  
  conditionalFormatting(wb, 
                        sheet_name ,
                        cols  = 4,
                        rows  = 1:(nrow(dat_sht) + 1), 
                        rule  = "off", type = "contains",
                        style = createStyle(bgFill = "#00B0F0"))
  
  conditionalFormatting(wb, 
                        sheet_name ,
                        cols = 4,
                        rows = 1:(nrow(dat_sht) + 1), 
                        rule = "mid", type = "contains",
                        style = createStyle(bgFill = "#FFC000"))
  
  if (length(dup_rows) < 1) next
  
  for (j in dup_rows) {
     addStyle(wb, 
              sheet_name,
              cols = 1:3,
              rows = j + 1, 
              stack = TRUE,
              style = createStyle(fgFill = "#F4B084"))
    
    
     addStyle(wb, 
              sheet_name ,
              cols = 1:3,
              rows = j, 
              stack = TRUE,
              style = createStyle(fgFill = "#C6E0B4"))
  }
}

openXL(wb)
```

```{r}
if (FALSE) {
  saveWorkbook(wb, schedule_file,
             overwrite = TRUE)
}

schedule_file |> shell.exec()
```

