---
title: "Read All Meta for eDNA"
author: "Sebastian DiGeronimo"
date: '2022-09-13'
output: html_document
---

# TODO: format like merge_data.Rmd
# Load Libraries
```{r setup}
librarian::shelf(
  librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  forcats, lubridate, glue, fs, magrittr, here,
  # broom # optional
  
  # additional
  readxl
)

library("conflicted")

conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")

```

# Search files
```{r find-files}
files <-
  dir_ls(here("data/metadata/WS_all/"),
         regexp  = "^[^~]*\\.(xlsx)$",
         recurse = TRUE) %>%
  tibble(files = ., 
         base  = basename(.)) %>%

  # ignore some files
  filter(str_detect(basename(files), "fknms_") &
         !str_detect(files, "ignore"))

# files to be read
files$base
```
# Extract sheet name and row to read
```{r sheet-info}
recal <- tibble(file = NA, sht_num = NA, row = NA, last_c = NA)

for (i in seq(nrow(files))) {
# for (i in 1) {
  
  # select sheet name with `field_logsheet`
  cli::cli_alert_info("Getting sheet info for file: {.file {files$base[i]}}")
  temp_sht <- excel_sheets(files$files[i]) 
  sht_num <- which(str_detect(temp_sht, "field_"))
  
  if (is_empty(sht_num)) {
    sht_num <- menu(temp_sht, 
                     title = glue(
                       "\n-----\n\n",
                       "Which sheet contains metadata?", 
                       "\n(0 for none)"))
  }
  
  # skip if no sheet name
  if (sht_num == 0) {
    recal <- add_row(recal,
    tibble(file = files$files[i], sht_num = NA, row = NA, last_c = NA) )
    next
  }
  
  # read sheet 
  temp <- read_excel(
    files$files[i],
    sheet        = sht_num, 
    n_max        = 5,
    col_names    = FALSE,
    .name_repair = "unique_quiet") 
  
  # name <- files$files[i]
  
  # row number that contains headers
  row <- which(apply(temp, 1, function(x) any(grepl("(?i)sample", x))))
  
  if (is_empty(row) || is.na(row)) {
    View(temp)
    row <- readline("Which line is the header? ") %>%
           as.numeric()
  }
  
  # skip if no row info
  if (is_empty(row) || is.na(row)) {
    recal <- 
      add_row(recal, 
              tibble(file    = files$files[i], 
                     sht_num = sht_num, 
                     row     = NA, 
                     last_c  = NA))
    next
    }
  
  # get last column number
  last_c <- which(grepl("(?i)notes", temp[row,])) 

  recal <- 
    add_row(
      recal,
      tibble(file = files$files[i], sht_num = sht_num, row = row, last_c = last_c)
    )
}

files <- recal %>%
  drop_na(everything()) %>%
  left_join(files, by = c("file" = "files"))
```

```{r}
# `NA` values to skip
na_skip <- c("NA", "Skipped", "skipped", "na", "n/a", "n./a", "n.a", "Flow", "*",
             stringi::stri_dup("-", 1:20))

header <- tibble(`names(temp)` = NA)
store <- list()


for (i in seq(nrow(files))) {
  temp <- read_xlsx(
    files$file[i],
    sheet        = files$sht_num[i],
    skip         = files$row[i] - 1,
    range        = cell_cols(c(NA, files$last_c[i])),
    .name_repair = janitor::make_clean_names,
    na           = na_skip
  ) %>%
  
  filter(str_detect(identifier, "WS|SV|WB")) %>%

  # select(-any_of(c("x", "wb", "ws", "x_2", "x_3", "x_4", "x_5",  "x_6",  "x_7", "x_8",
  #                  "x_9", "nov",
  #                  "x21338","x22022", "x22072",
  #                  "x22141", "x22215", "max_depth", "depth_m" )
  #                )
  #        )  %>%
 
  mutate(
    # across(where(is.character), ~ replace(., str_detect(., "--|\\*|Skipped"), NA)),
    vol_ml = replace(vol_ml,  str_detect(vol_ml, "-"), NA),
    vol_ml = str_replace_all(vol_ml, "~", "")
    ) %>%
  type_convert() %>%
  mutate(
      notes = as.character(notes)
    )  %>%
    rename(any_of(c(sample_collection_time_gmt = "time_gmt")))
}
 typeof(temp$vol_ml) == "character" 
  if (files$base[i] == "fknms_sample_logsheet_OCT2017.xlsx") {
    temp %<>%
    mutate(vol_ml = strsplit(as.character(vol_ml), "&")) %>%
      unnest(vol_ml) %>%
      mutate(vol_ml = str_trim(vol_ml)) %>%
      type_convert()
  }

  # if (basename(files[i]) == "fknms_logsheet_OCT2018.xlsx") temp %<>%
  # rename("sample_collection_time_gmt" = time_gmt)
  
tibble(time_gmt = 1) %>%
  

  if (basename(files[i]) == "fknms_sample_logsheet_07_08_2021.xlsx") temp %<>% 
    replace_na(list(depth_m = 1))

  
  store$fknms_sample_logsheet_07_08_2021.xlsx %>%
  replace_na(list(depth_m = 1))
  
  
  name <- basename(files[i])
  store[[name]] <- temp
  
  header <- bind_rows(header, as.data.frame(names(temp)))
  
}

merge_by <- header %>%
  group_by(`names(temp)`) %>%
summarise(count = n()) %>%
  filter(count > 32) %$% 
  `names(temp)`

mismatch <- t(janitor::compare_df_cols(store, 
                         return = "mismatch"))
                         
                         
                         
mismatch

# TODO: add log stuff here to fix mismatches
```
```{r}


# i = which(basename(files) == "fknms_sample_logsheet_12_2021.xlsx")
store$fknms_logsheet_OCT2018.xlsx



```

```{r}

store_merg <- reduce(store, full_join) %>%
  filter(date_mm_dd_yy != as_date("1899-12-31 00:00:00"))


store_merg %>%
  filter(!is.na(date_mm_dd_yy), !is.na(sample_collection_time_gmt)) %>%
  # filter(sample_type != "CDOM", is.na(vol_ml))
  group_by(sample_type) %>%
  distinct() %>%
  summarise(total = n())
  
test <- store_merg %>%
  filter(!is.na(date_mm_dd_yy), !is.na(sample_collection_time_gmt)) %>%
  # filter(sample_type != "CDOM", is.na(vol_ml))
  group_by(sample_type) %>%
  distinct()
# %>%
  # summarise(total = n())

store_merg %>% 
  # arrange(date_mm_dd_yy)
  filter(date_mm_dd_yy <= as_date("2019-07-19")) %>%
  group_by(sample_type) %>%
  
  summarise(n = n())



store_merg %>%
  filter(sample_type == "Chl-a", 
         !is.na(vol_ml),
         date_mm_dd_yy != as_date("1899-12-31 00:00:00")
         ) %>%
  distinct(identifier, .keep_all = T) %>%
  arrange(date_mm_dd_yy)

```

```{r}
source("../scripts/log_file_changes.R")
startup()
current_log()
log4r_info(verbose = FALSE)

read.delim("../data_change_logfile.txt")
```

