---
title: "Cruise Setup"
author: "Sebastian Di Geronimo"
format: html
editor: source
---

## Setup

This files is used to setup the file structure and set the cloud directory path 
in the **.Rprofile** so that each *reset* of Rstudio will set the **cloud_dir** 
as a variable itself.

```{r}
if (!nzchar(system.file(package = "librarian"))) 
  install.packages("librarian")

librarian::shelf(
  librarian, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  forcats, lubridate, glue, fs, magrittr, here,
  
  # broom # optional
  
  # added
  ggrepel, ggtext, readxl, ggnewscale, cli,
  
  # idk if needed
  fields, raster, rerddap, rgdal, ncdf4, sf, metR, cowplot, anytime, 
  parzer, openxlsx2, ggthemes, 
)
```


```{r}
source(here::here("scripts", "create_dir.R"))

cloud_dir <- rstudioapi::selectDirectory(
  caption = "set your local box.com/imars_mbon_cruises folder mount",
  label = "this is my box.com/imars_mbon_cruises location"
)

local_dir <- rstudioapi::selectDirectory(
  caption = "set your location for cruise data",
  label = "this is my local location for cruise data"
)



cat(glue::glue("cloud_dir <- \"{cloud_dir}\"\nlocal_dir <- \"{local_dir}\""), 
    file = here::here(".Rprofile"))


cat(
'
CRUISE_ID=\"\"

cat(
"------------------\n",
"Welcome to MBON Cruise Prep Project!\n",
"Navigate to the protocol_workflow_tasks folder and select which process you are doing.\n",
"The options are:",
paste0("\t", fs::dir_ls(here::here("protocol_workflow_tasks"), 
                        type = "directory") |> 
  stringr::str_subset("old", negate = TRUE) |> 
  basename() |> sort(decreasing = TRUE)),
"\n------------------\n",
sep = "\n"
)',
file = here::here(".Rprofile"),
append = TRUE
)

```
